#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sbt-interface
Version  : 0.13.15
Release  : 1
URL      : https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-interface/0.13.15/sbt-interface-0.13.15.jar
Source0  : https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-interface/0.13.15/sbt-interface-0.13.15.jar
Source1  : https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-interface/0.13.15/sbt-interface-0.13.15.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-sbt-interface-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sbt-interface package.
Group: Data

%description data
data components for the mvn-sbt-interface package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/sbt-interface/0.13.15
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/sbt-interface/0.13.15/sbt-interface-0.13.15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/sbt-interface/0.13.15
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/sbt/sbt-interface/0.13.15/sbt-interface-0.13.15.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/typesafe/sbt/sbt-interface/0.13.15/sbt-interface-0.13.15.jar
/usr/share/java/.m2/repository/com/typesafe/sbt/sbt-interface/0.13.15/sbt-interface-0.13.15.pom
